/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForBrandsRouteImport } from './routes/for-brands'
import { Route as ForCreatorsRouteImport } from './routes/for-creators'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedMatchesRouteImport } from './routes/_authenticated/matches'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationPreferencesRouteImport } from './routes/_authenticated/notification-preferences'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedTrendsRouteImport } from './routes/_authenticated/trends'
import { Route as AuthenticatedBrandsBrandIdRouteImport } from './routes/_authenticated/brands.$brandId'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns.index'
import { Route as AuthenticatedCampaignsCampaignIdRouteImport } from './routes/_authenticated/campaigns.$campaignId'
import { Route as AuthenticatedCheckoutPaymentIdRouteImport } from './routes/_authenticated/checkout.$paymentId'
import { Route as AuthenticatedCreatorsCreatorIdRouteImport } from './routes/_authenticated/creators.$creatorId'
import { Route as AuthenticatedDealsIndexRouteImport } from './routes/_authenticated/deals.index'
import { Route as AuthenticatedDealsDealIdRouteImport } from './routes/_authenticated/deals.$dealId'
import { Route as ApiPublicInstagramCallbackRouteImport } from './routes/api/public/instagram/callback'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBrandsRoute = ForBrandsRouteImport.update({
  id: '/for-brands',
  path: '/for-brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCreatorsRoute = ForCreatorsRouteImport.update({
  id: '/for-creators',
  path: '/for-creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchesRoute = AuthenticatedMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationPreferencesRoute =
  AuthenticatedNotificationPreferencesRouteImport.update({
    id: '/notification-preferences',
    path: '/notification-preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrendsRoute = AuthenticatedTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsBrandIdRoute =
  AuthenticatedBrandsBrandIdRouteImport.update({
    id: '/brands/$brandId',
    path: '/brands/$brandId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdRoute =
  AuthenticatedCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckoutPaymentIdRoute =
  AuthenticatedCheckoutPaymentIdRouteImport.update({
    id: '/checkout/$paymentId',
    path: '/checkout/$paymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreatorsCreatorIdRoute =
  AuthenticatedCreatorsCreatorIdRouteImport.update({
    id: '/creators/$creatorId',
    path: '/creators/$creatorId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDealsIndexRoute = AuthenticatedDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsDealIdRoute =
  AuthenticatedDealsDealIdRouteImport.update({
    id: '/deals/$dealId',
    path: '/deals/$dealId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicInstagramCallbackRoute =
  ApiPublicInstagramCallbackRouteImport.update({
    id: '/api/public/instagram/callback',
    path: '/api/public/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/for-brands': typeof ForBrandsRoute
  '/for-creators': typeof ForCreatorsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notification-preferences': typeof AuthenticatedNotificationPreferencesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/brands/$brandId': typeof AuthenticatedBrandsBrandIdRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/checkout/$paymentId': typeof AuthenticatedCheckoutPaymentIdRoute
  '/creators/$creatorId': typeof AuthenticatedCreatorsCreatorIdRoute
  '/deals/$dealId': typeof AuthenticatedDealsDealIdRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/deals/': typeof AuthenticatedDealsIndexRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/for-brands': typeof ForBrandsRoute
  '/for-creators': typeof ForCreatorsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notification-preferences': typeof AuthenticatedNotificationPreferencesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/brands/$brandId': typeof AuthenticatedBrandsBrandIdRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/checkout/$paymentId': typeof AuthenticatedCheckoutPaymentIdRoute
  '/creators/$creatorId': typeof AuthenticatedCreatorsCreatorIdRoute
  '/deals/$dealId': typeof AuthenticatedDealsDealIdRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/deals': typeof AuthenticatedDealsIndexRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/for-brands': typeof ForBrandsRoute
  '/for-creators': typeof ForCreatorsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/matches': typeof AuthenticatedMatchesRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notification-preferences': typeof AuthenticatedNotificationPreferencesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/trends': typeof AuthenticatedTrendsRoute
  '/_authenticated/brands/$brandId': typeof AuthenticatedBrandsBrandIdRoute
  '/_authenticated/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRoute
  '/_authenticated/checkout/$paymentId': typeof AuthenticatedCheckoutPaymentIdRoute
  '/_authenticated/creators/$creatorId': typeof AuthenticatedCreatorsCreatorIdRoute
  '/_authenticated/deals/$dealId': typeof AuthenticatedDealsDealIdRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/deals/': typeof AuthenticatedDealsIndexRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/for-brands'
    | '/for-creators'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/connections'
    | '/dashboard'
    | '/discover'
    | '/feed'
    | '/matches'
    | '/messages'
    | '/notification-preferences'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/support'
    | '/trends'
    | '/brands/$brandId'
    | '/campaigns/$campaignId'
    | '/checkout/$paymentId'
    | '/creators/$creatorId'
    | '/deals/$dealId'
    | '/campaigns/'
    | '/deals/'
    | '/api/public/instagram/callback'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/for-brands'
    | '/for-creators'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/connections'
    | '/dashboard'
    | '/discover'
    | '/feed'
    | '/matches'
    | '/messages'
    | '/notification-preferences'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/support'
    | '/trends'
    | '/brands/$brandId'
    | '/campaigns/$campaignId'
    | '/checkout/$paymentId'
    | '/creators/$creatorId'
    | '/deals/$dealId'
    | '/campaigns'
    | '/deals'
    | '/api/public/instagram/callback'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/faq'
    | '/for-brands'
    | '/for-creators'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/connections'
    | '/_authenticated/dashboard'
    | '/_authenticated/discover'
    | '/_authenticated/feed'
    | '/_authenticated/matches'
    | '/_authenticated/messages'
    | '/_authenticated/notification-preferences'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/support'
    | '/_authenticated/trends'
    | '/_authenticated/brands/$brandId'
    | '/_authenticated/campaigns/$campaignId'
    | '/_authenticated/checkout/$paymentId'
    | '/_authenticated/creators/$creatorId'
    | '/_authenticated/deals/$dealId'
    | '/_authenticated/campaigns/'
    | '/_authenticated/deals/'
    | '/api/public/instagram/callback'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  ForBrandsRoute: typeof ForBrandsRoute
  ForCreatorsRoute: typeof ForCreatorsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicInstagramCallbackRoute: typeof ApiPublicInstagramCallbackRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-brands': {
      id: '/for-brands'
      path: '/for-brands'
      fullPath: '/for-brands'
      preLoaderRoute: typeof ForBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-creators': {
      id: '/for-creators'
      path: '/for-creators'
      fullPath: '/for-creators'
      preLoaderRoute: typeof ForCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches': {
      id: '/_authenticated/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notification-preferences': {
      id: '/_authenticated/notification-preferences'
      path: '/notification-preferences'
      fullPath: '/notification-preferences'
      preLoaderRoute: typeof AuthenticatedNotificationPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trends': {
      id: '/_authenticated/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedTrendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/$brandId': {
      id: '/_authenticated/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof AuthenticatedBrandsBrandIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/$campaignId': {
      id: '/_authenticated/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/$paymentId': {
      id: '/_authenticated/checkout/$paymentId'
      path: '/checkout/$paymentId'
      fullPath: '/checkout/$paymentId'
      preLoaderRoute: typeof AuthenticatedCheckoutPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creators/$creatorId': {
      id: '/_authenticated/creators/$creatorId'
      path: '/creators/$creatorId'
      fullPath: '/creators/$creatorId'
      preLoaderRoute: typeof AuthenticatedCreatorsCreatorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals/': {
      id: '/_authenticated/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof AuthenticatedDealsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals/$dealId': {
      id: '/_authenticated/deals/$dealId'
      path: '/deals/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof AuthenticatedDealsDealIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/instagram/callback': {
      id: '/api/public/instagram/callback'
      path: '/api/public/instagram/callback'
      fullPath: '/api/public/instagram/callback'
      preLoaderRoute: typeof ApiPublicInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedMatchesRoute: typeof AuthenticatedMatchesRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationPreferencesRoute: typeof AuthenticatedNotificationPreferencesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTrendsRoute: typeof AuthenticatedTrendsRoute
  AuthenticatedBrandsBrandIdRoute: typeof AuthenticatedBrandsBrandIdRoute
  AuthenticatedCampaignsCampaignIdRoute: typeof AuthenticatedCampaignsCampaignIdRoute
  AuthenticatedCheckoutPaymentIdRoute: typeof AuthenticatedCheckoutPaymentIdRoute
  AuthenticatedCreatorsCreatorIdRoute: typeof AuthenticatedCreatorsCreatorIdRoute
  AuthenticatedDealsDealIdRoute: typeof AuthenticatedDealsDealIdRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
  AuthenticatedDealsIndexRoute: typeof AuthenticatedDealsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedMatchesRoute: AuthenticatedMatchesRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationPreferencesRoute:
    AuthenticatedNotificationPreferencesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTrendsRoute: AuthenticatedTrendsRoute,
  AuthenticatedBrandsBrandIdRoute: AuthenticatedBrandsBrandIdRoute,
  AuthenticatedCampaignsCampaignIdRoute: AuthenticatedCampaignsCampaignIdRoute,
  AuthenticatedCheckoutPaymentIdRoute: AuthenticatedCheckoutPaymentIdRoute,
  AuthenticatedCreatorsCreatorIdRoute: AuthenticatedCreatorsCreatorIdRoute,
  AuthenticatedDealsDealIdRoute: AuthenticatedDealsDealIdRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
  AuthenticatedDealsIndexRoute: AuthenticatedDealsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  ForBrandsRoute: ForBrandsRoute,
  ForCreatorsRoute: ForCreatorsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicInstagramCallbackRoute: ApiPublicInstagramCallbackRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
